#debug: true
spring:
#  security:
#    user:
#      password: "test"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  datasource:
#    url: jdbc:sqlite:./demo-db.sqlite
#    username:
#    password:
#    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      format_sql: true
#    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

#Custom properties
application:
  security:
    jwt:
      secret_key: exSRp86C5hvwE8RvcLObLzk0MvJElfXPOpWDWqkU+nw=
      expiration: 816400000 #1 day
      refresh_token:
        secret_key: o4ZaO5wwpAYep8S2fkxcR79AXS6nxOW8PNfaeDjSURs=
        expiration: 259200000 #3 days
  corsAllowedOrigins: '${Angular_WEB_ORIGIN:http://localhost:4200}'
